# Generated by Django 6.0.1 on 2026-01-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='display_order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
